--Database, Schemas & Warehouse

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS NOAA_WEATHER_DB;
USE DATABASE NOAA_WEATHER_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS DATA_MART;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SECURITY;

CREATE WAREHOUSE IF NOT EXISTS NOAA_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;  
