--RBAC (Roles Setup)

USE WAREHOUSE NOAA_WH;
USE ROLE ACCOUNTADMIN;
USE DATABASE NOAA_WEATHER_DB;

CREATE ROLE IF NOT EXISTS NOAA_SYSADMIN; --NOAA_WEATHER_DB DATABASE SYSADMIN ROLE
CREATE ROLE IF NOT EXISTS NOAA_ENGINEER; --NOAA_WEATHER_DB Architect + Data steward ROLE
CREATE ROLE IF NOT EXISTS NOAA_ANALYST;  --ANALYTICS LAYER RO ROLE 

GRANT ALL PRIVILEGES ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_SYSADMIN;


GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE TO ROLE NOAA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_MART TO ROLE NOAA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE NOAA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA STAGING TO ROLE NOAA_ENGINEER;

-- Monitoring DQ grants (including direct) needed for DATA METRIC FUNCTION and scheduled tasks execution
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE NOAA_ENGINEER;
-- Also grant usage so the role can read system DMFs
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE NOAA_ENGINEER;


-- DATA_MART access
GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ENGINEER;
GRANT USAGE ON SCHEMA NOAA_WEATHER_DB.DATA_MART TO ROLE NOAA_ENGINEER;
GRANT SELECT ON TABLE NOAA_WEATHER_DB.DATA_MART.FACT_WEATHER_DAILY TO ROLE NOAA_ENGINEER;

-- MONITORING access
GRANT USAGE ON SCHEMA NOAA_WEATHER_DB.MONITORING TO ROLE NOAA_ENGINEER;
GRANT INSERT ON TABLE NOAA_WEATHER_DB.MONITORING.DATA_QUALITY_RESULTS TO ROLE NOAA_ENGINEER;


-- NOAA_ANALYST Architect ROLE PRIVILEGES
GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ENGINEER;
GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE TASK, CREATE STREAM, CREATE ROW ACCESS POLICY, CREATE MASKING POLICY, CREATE TAG
    ON ALL SCHEMAS IN DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ENGINEER;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE NOAA_ENGINEER;
GRANT APPLY TAG ON ACCOUNT TO ROLE NOAA_ENGINEER;  
GRANT EXECUTE TASK on ACCOUNT to role NOAA_ENGINEER;

-- NOAA_ANALYST RO ROLE PRIVILEGES
GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ANALYST;
GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ANALYST;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE NOAA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS TO ROLE NOAA_ANALYST;

-- RO roles with access to subset of data based on US stataes (west/central/east) in ANALYTICS LAYER

CREATE ROLE IF NOT EXISTS NOAA_ANALYST_WEST;
CREATE ROLE IF NOT EXISTS NOAA_ANALYST_CENTRAL;   
CREATE ROLE IF NOT EXISTS NOAA_ANALYST_EAST;   

GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ANALYST_WEST;
GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ANALYST_CENTRAL;
GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ANALYST_EAST; 

GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ANALYST_WEST;
GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ANALYST_CENTRAL;
GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ANALYST_EAST;

GRANT USAGE ON SCHEMA ANALYTICS TO ROLE NOAA_ANALYST_WEST;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE NOAA_ANALYST_CENTRAL;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE NOAA_ANALYST_EAST;

GRANT SELECT ON ALL VIEWS IN SCHEMA NOAA_WEATHER_DB.ANALYTICS TO ROLE NOAA_ANALYST_WEST;
GRANT SELECT ON ALL VIEWS IN SCHEMA NOAA_WEATHER_DB.ANALYTICS TO ROLE NOAA_ANALYST_CENTRAL;
GRANT SELECT ON ALL VIEWS IN SCHEMA NOAA_WEATHER_DB.ANALYTICS TO ROLE NOAA_ANALYST_EAST;

GRANT USAGE ON SCHEMA SECURITY TO ROLE NOAA_ANALYST_WEST;
GRANT USAGE ON SCHEMA SECURITY TO ROLE NOAA_ANALYST_CENTRAL;
GRANT USAGE ON SCHEMA SECURITY TO ROLE NOAA_ANALYST_EAST;

GRANT SELECT ON SECURITY.STATE_ACCESS_MAP TO ROLE NOAA_ANALYST_WEST;
GRANT SELECT ON SECURITY.STATE_ACCESS_MAP TO ROLE NOAA_ANALYST_CENTRAL;
GRANT SELECT ON SECURITY.STATE_ACCESS_MAP TO ROLE NOAA_ANALYST_EAST;
 
 --Roles needed to be granted to one or more organization user/s who log/s in to snowflake account and perform different actions
 
 --GRANT ROLE NOAA_SYSADMIN TO USER <snowflake connected user>;
 --GRANT ROLE NOAA_ENGINEER TO USER <snowflake connected user>;
 --GRANT ROLE NOAA_ANALYST TO USER  <snowflake connected user>;
 --GRANT ROLE NOAA_ANALYST_WEST TO USER <snowflake connected user>;
 --GRANT ROLE NOAA_ANALYST_CENTRAL TO USER <snowflake connected user>;
 --GRANT ROLE NOAA_ANALYST_EAST TO USER  <snowflake connected user>;
