--RBAC (Roles Setup)

USE WAREHOUSE NOAA_WH;
USE ROLE ACCOUNTADMIN;
USE DATABASE NOAA_WEATHER_DB;

CREATE ROLE IF NOT EXISTS NOAA_SYSADMIN;
CREATE ROLE IF NOT EXISTS NOAA_ENGINEER;
CREATE ROLE IF NOT EXISTS NOAA_ANALYST;

GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ENGINEER;
GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ANALYST;

GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE TO ROLE NOAA_ENGINEER;

GRANT ALL PRIVILEGES ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_SYSADMIN;

GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ENGINEER;

GRANT CREATE TABLE, CREATE VIEW, CREATE TASK, CREATE STREAM, CREATE ROW ACCESS POLICY
  ON ALL SCHEMAS IN DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ENGINEER;
  
GRANT EXECUTE TASK on account to role NOAA_ENGINEER;

GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ANALYST;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE NOAA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS TO ROLE NOAA_ANALYST;

CREATE ROLE IF NOT EXISTS NOAA_ANALYST_WEST;
CREATE ROLE IF NOT EXISTS NOAA_ANALYST_CENTRAL;   
CREATE ROLE IF NOT EXISTS NOAA_ANALYST_EAST;   

GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ANALYST_WEST;
GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ANALYST_CENTRAL;
GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ANALYST_EAST; 

GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ANALYST_WEST;
GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ANALYST_CENTRAL;
GRANT USAGE ON DATABASE NOAA_WEATHER_DB TO ROLE NOAA_ANALYST_EAST;

GRANT USAGE ON SCHEMA ANALYTICS TO ROLE NOAA_ANALYST_WEST;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE NOAA_ANALYST_CENTRAL;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE NOAA_ANALYST_EAST;

GRANT SELECT ON ALL VIEWS IN SCHEMA NOAA_WEATHER_DB.ANALYTICS TO ROLE NOAA_ANALYST_WEST;
GRANT SELECT ON ALL VIEWS IN SCHEMA NOAA_WEATHER_DB.ANALYTICS TO ROLE NOAA_ANALYST_CENTRAL;
GRANT SELECT ON ALL VIEWS IN SCHEMA NOAA_WEATHER_DB.ANALYTICS TO ROLE NOAA_ANALYST_EAST;

GRANT USAGE ON SCHEMA SECURITY TO ROLE NOAA_ANALYST_WEST;
GRANT USAGE ON SCHEMA SECURITY TO ROLE NOAA_ANALYST_CENTRAL;
GRANT USAGE ON SCHEMA SECURITY TO ROLE NOAA_ANALYST_EAST;

GRANT SELECT ON SECURITY.STATE_ACCESS_MAP TO ROLE NOAA_ANALYST_WEST;
GRANT SELECT ON SECURITY.STATE_ACCESS_MAP TO ROLE NOAA_ANALYST_CENTRAL;
GRANT SELECT ON SECURITY.STATE_ACCESS_MAP TO ROLE NOAA_ANALYST_EAST;
 
 --GRANT ROLE NOAA_SYSADMIN TO USER <csnowlake connected user>;
 --GRANT ROLE NOAA_ENGINEER TO USER <csnowlake connected user>;
 --GRANT ROLE NOAA_ANALYST TO USER  <csnowlake connected user>;
 --GRANT ROLE NOAA_ANALYST_WEST TO USER <csnowlake connected user>;
 --GRANT ROLE NOAA_ANALYST_CENTRAL TO USER <csnowlake connected user>;
 --GRANT ROLE NOAA_ANALYST_EAST TO USER  <csnowlake connected user>;
