-- Tag based masking policies setup

USE WAREHOUSE NOAA_WH;
USE ROLE NOAA_ENGINEER;
USE DATABASE NOAA_WEATHER_DB;
USE SCHEMA SECURITY;

--PII / Sensitive Data Tags
CREATE OR REPLACE TAG SECURITY.PII_CLASS
ALLOWED_VALUES 'NONE', 'LOW', 'HIGH';

--DATA_DOMAIN Tag (Table-Level Classification)
CREATE OR REPLACE TAG SECURITY.DATA_DOMAIN
ALLOWED_VALUES 'WEATHER', 'WATER_SUPPLY', 'REFERENCE';

--Sensitivity Masking Policy (Tag-Based + Domain-Aware Masking Logic)
CREATE OR REPLACE MASKING POLICY SECURITY.MP_PII_CLASS
AS (val STRING)
RETURNS STRING ->
  CASE
    -- Non-sensitive data
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('SECURITY.PII_CLASS') = 'NONE'
      THEN val

    -- WEATHER domain, LOW sensitivity
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('SECURITY.PII_CLASS') = 'LOW'
     AND SYSTEM$GET_TAG_ON_CURRENT_TABLE('SECURITY.DATA_DOMAIN') = 'WEATHER'
     AND CURRENT_ROLE() IN ('NOAA_ENGINEER','NOAA_ANALYST')
      THEN val  

    -- HIGH sensitivity (any domain)
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('SECURITY.PII_CLASS') = 'HIGH'
     AND CURRENT_ROLE() = 'NOAA_ENGINEER'
      THEN val

    ELSE '***MASKED***'
  END;
    
-- Assign Tag-Based masking policy
ALTER TAG SECURITY.PII_CLASS
SET MASKING POLICY SECURITY.MP_PII_CLASS;
  
--Apply Tags & Bind Policies
---DATA_MART layer
ALTER TABLE DATA_MART.FACT_WEATHER_DAILY
MODIFY COLUMN station_id
SET TAG SECURITY.PII_CLASS = 'LOW';

ALTER TABLE DATA_MART.DIM_STATION
MODIFY COLUMN station_id
SET TAG SECURITY.PII_CLASS = 'LOW';

--Apply DATA_DOMAIN Tag at TABLE Level

---RAW Layer
ALTER TABLE RAW.NOAA_WEATHER_METRICS_TS
SET TAG SECURITY.DATA_DOMAIN = 'WEATHER';

ALTER TABLE RAW.NOAA_WATER_SUPPLY_TS
SET TAG SECURITY.DATA_DOMAIN = 'WATER_SUPPLY';

ALTER TABLE RAW.NOAA_WEATHER_STATION_INDEX
SET TAG SECURITY.DATA_DOMAIN = 'REFERENCE';

---STAGING Layer
ALTER TABLE STAGING.STG_WEATHER_METRICS
SET TAG SECURITY.DATA_DOMAIN = 'WEATHER';

ALTER TABLE STAGING.STG_WEATHER_STATIONS
SET TAG SECURITY.DATA_DOMAIN = 'WEATHER';

---DATA_MART Layer
ALTER TABLE DATA_MART.FACT_WEATHER_DAILY
SET TAG SECURITY.DATA_DOMAIN = 'WEATHER';

ALTER TABLE DATA_MART.DIM_STATION
SET TAG SECURITY.DATA_DOMAIN = 'WEATHER';
